EESchema Schematic File Version 4
EELAYER 30 0
EELAYER END
$Descr A3 16535 11693
encoding utf-8
Sheet 1 1
Title "Telearm Wiring Harness (Module-level)"
Date "2026-01-10"
Rev "A"
Comp "Prototype wiring – NOT for clinical use"
Comment1 "Robot-side: ESP32-S3 + TB6600×4 + PCA9685 + TCA9548A + AS5600×6 + CAN"
Comment2 "Master-side: ESP32-S3 + user manipulator sensors + CAN"
Comment3 "Generated by ChatGPT (legacy KiCad schematic scaffold)"
$EndDescr
$Comp
L Connector_Generic:Conn_01x02 J_PWR24
U 1 1 95F2565B
P 1100 900
F 0 "J_PWR24" H 1180 950 50  0000 L CNN
F 1 "24V_IN (Motor Rail)" H 1180 850 50  0000 L CNN
F 2 "" H 1100 900 50  0001 C CNN
F 3 "~" H 1100 900 50  0001 C CNN
	1    1100 900
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x02 J_PWR6
U 1 1 A262808F
P 1100 1250
F 0 "J_PWR6" H 1180 1300 50  0000 L CNN
F 1 "6-8.4V_IN (Servo Rail)" H 1180 1200 50  0000 L CNN
F 2 "" H 1100 1250 50  0001 C CNN
F 3 "~" H 1100 1250 50  0001 C CNN
	1    1100 1250
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x02 J_PWR5
U 1 1 DAC720EC
P 1100 1600
F 0 "J_PWR5" H 1180 1650 50  0000 L CNN
F 1 "5V_IN (Logic Rail)" H 1180 1550 50  0000 L CNN
F 2 "" H 1100 1600 50  0001 C CNN
F 3 "~" H 1100 1600 50  0001 C CNN
	1    1100 1600
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x03 J_ESTOP
U 1 1 738AFF04
P 1100 1950
F 0 "J_ESTOP" H 1180 2000 50  0000 L CNN
F 1 "E-STOP (NC loop)" H 1180 1900 50  0000 L CNN
F 2 "" H 1100 1950 50  0001 C CNN
F 3 "~" H 1100 1950 50  0001 C CNN
	1    1100 1950
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_02x22_Odd_Even J_ROBOT
U 1 1 3F765185
P 4200 1050
F 0 "J_ROBOT" H 4280 1100 50  0000 L CNN
F 1 "Robot ESP32-S3 Header (generic)" H 4280 1000 50  0000 L CNN
F 2 "" H 4200 1050 50  0001 C CNN
F 3 "~" H 4200 1050 50  0001 C CNN
	1    4200 1050
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_02x22_Odd_Even J_MASTER
U 1 1 E337FBEC
P 4200 3350
F 0 "J_MASTER" H 4280 3400 50  0000 L CNN
F 1 "Master ESP32-S3 Header (generic)" H 4280 3300 50  0000 L CNN
F 2 "" H 4200 3350 50  0001 C CNN
F 3 "~" H 4200 3350 50  0001 C CNN
	1    4200 3350
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x04 J_CAN_XCVR
U 1 1 8DCB6DA3
P 7200 1050
F 0 "J_CAN_XCVR" H 7280 1100 50  0000 L CNN
F 1 "CAN Transceiver Module (SN65HVD230 class)" H 7280 1000 50  0000 L CNN
F 2 "" H 7200 1050 50  0001 C CNN
F 3 "~" H 7200 1050 50  0001 C CNN
	1    7200 1050
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x03 J_CAN_BUS
U 1 1 2FCD1170
P 7200 1500
F 0 "J_CAN_BUS" H 7280 1550 50  0000 L CNN
F 1 "CAN BUS OUT (CANH/CANL/GND)" H 7280 1450 50  0000 L CNN
F 2 "" H 7200 1500 50  0001 C CNN
F 3 "~" H 7200 1500 50  0001 C CNN
	1    7200 1500
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_PCA9685
U 1 1 73E2C8D4
P 7200 2400
F 0 "J_PCA9685" H 7280 2450 50  0000 L CNN
F 1 "PCA9685 PWM Driver" H 7280 2350 50  0000 L CNN
F 2 "" H 7200 2400 50  0001 C CNN
F 3 "~" H 7200 2400 50  0001 C CNN
	1    7200 2400
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x08 J_TCA9548A
U 1 1 ECBA3693
P 7200 3200
F 0 "J_TCA9548A" H 7280 3250 50  0000 L CNN
F 1 "TCA9548A I2C Mux" H 7280 3150 50  0000 L CNN
F 2 "" H 7200 3200 50  0001 C CNN
F 3 "~" H 7200 3200 50  0001 C CNN
	1    7200 3200
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_ENC1
U 1 1 6785A9E4
P 10300 800
F 0 "J_ENC1" H 10380 850 50  0000 L CNN
F 1 "AS5600 Encoder #1" H 10380 750 50  0000 L CNN
F 2 "" H 10300 800 50  0001 C CNN
F 3 "~" H 10300 800 50  0001 C CNN
	1    10300 800
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_ENC2
U 1 1 406AD718
P 10300 1450
F 0 "J_ENC2" H 10380 1500 50  0000 L CNN
F 1 "AS5600 Encoder #2" H 10380 1400 50  0000 L CNN
F 2 "" H 10300 1450 50  0001 C CNN
F 3 "~" H 10300 1450 50  0001 C CNN
	1    10300 1450
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_ENC3
U 1 1 21E8D839
P 10300 2100
F 0 "J_ENC3" H 10380 2150 50  0000 L CNN
F 1 "AS5600 Encoder #3" H 10380 2050 50  0000 L CNN
F 2 "" H 10300 2100 50  0001 C CNN
F 3 "~" H 10300 2100 50  0001 C CNN
	1    10300 2100
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_ENC4
U 1 1 1C04F4E2
P 10300 2750
F 0 "J_ENC4" H 10380 2800 50  0000 L CNN
F 1 "AS5600 Encoder #4" H 10380 2700 50  0000 L CNN
F 2 "" H 10300 2750 50  0001 C CNN
F 3 "~" H 10300 2750 50  0001 C CNN
	1    10300 2750
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_ENC5
U 1 1 E15F3ABF
P 10300 3400
F 0 "J_ENC5" H 10380 3450 50  0000 L CNN
F 1 "AS5600 Encoder #5" H 10380 3350 50  0000 L CNN
F 2 "" H 10300 3400 50  0001 C CNN
F 3 "~" H 10300 3400 50  0001 C CNN
	1    10300 3400
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_ENC6
U 1 1 197F502C
P 10300 4050
F 0 "J_ENC6" H 10380 4100 50  0000 L CNN
F 1 "AS5600 Encoder #6" H 10380 4000 50  0000 L CNN
F 2 "" H 10300 4050 50  0001 C CNN
F 3 "~" H 10300 4050 50  0001 C CNN
	1    10300 4050
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_TB1_CTRL
U 1 1 BE192CD5
P 10300 5200
F 0 "J_TB1_CTRL" H 10380 5250 50  0000 L CNN
F 1 "TB6600 #1 CTRL (PUL/DIR/ENA)" H 10380 5150 50  0000 L CNN
F 2 "" H 10300 5200 50  0001 C CNN
F 3 "~" H 10300 5200 50  0001 C CNN
	1    10300 5200
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_TB1_PWR
U 1 1 1E682461
P 12800 5200
F 0 "J_TB1_PWR" H 12880 5250 50  0000 L CNN
F 1 "TB6600 #1 PWR/MOTOR" H 12880 5150 50  0000 L CNN
F 2 "" H 12800 5200 50  0001 C CNN
F 3 "~" H 12800 5200 50  0001 C CNN
	1    12800 5200
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_TB2_CTRL
U 1 1 190A36D7
P 10300 5700
F 0 "J_TB2_CTRL" H 10380 5750 50  0000 L CNN
F 1 "TB6600 #2 CTRL (PUL/DIR/ENA)" H 10380 5650 50  0000 L CNN
F 2 "" H 10300 5700 50  0001 C CNN
F 3 "~" H 10300 5700 50  0001 C CNN
	1    10300 5700
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_TB2_PWR
U 1 1 7CA24385
P 12800 5700
F 0 "J_TB2_PWR" H 12880 5750 50  0000 L CNN
F 1 "TB6600 #2 PWR/MOTOR" H 12880 5650 50  0000 L CNN
F 2 "" H 12800 5700 50  0001 C CNN
F 3 "~" H 12800 5700 50  0001 C CNN
	1    12800 5700
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_TB3_CTRL
U 1 1 541C777F
P 10300 6200
F 0 "J_TB3_CTRL" H 10380 6250 50  0000 L CNN
F 1 "TB6600 #3 CTRL (PUL/DIR/ENA)" H 10380 6150 50  0000 L CNN
F 2 "" H 10300 6200 50  0001 C CNN
F 3 "~" H 10300 6200 50  0001 C CNN
	1    10300 6200
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_TB3_PWR
U 1 1 35C336A2
P 12800 6200
F 0 "J_TB3_PWR" H 12880 6250 50  0000 L CNN
F 1 "TB6600 #3 PWR/MOTOR" H 12880 6150 50  0000 L CNN
F 2 "" H 12800 6200 50  0001 C CNN
F 3 "~" H 12800 6200 50  0001 C CNN
	1    12800 6200
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_TB4_CTRL
U 1 1 EAF24733
P 10300 6700
F 0 "J_TB4_CTRL" H 10380 6750 50  0000 L CNN
F 1 "TB6600 #4 CTRL (PUL/DIR/ENA)" H 10380 6650 50  0000 L CNN
F 2 "" H 10300 6700 50  0001 C CNN
F 3 "~" H 10300 6700 50  0001 C CNN
	1    10300 6700
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x06 J_TB4_PWR
U 1 1 D12B2BF6
P 12800 6700
F 0 "J_TB4_PWR" H 12880 6750 50  0000 L CNN
F 1 "TB6600 #4 PWR/MOTOR" H 12880 6650 50  0000 L CNN
F 2 "" H 12800 6700 50  0001 C CNN
F 3 "~" H 12800 6700 50  0001 C CNN
	1    12800 6700
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x03 J_LS1
U 1 1 F2B5988F
P 1100 2500
F 0 "J_LS1" H 1180 2550 50  0000 L CNN
F 1 "Limit Switch J1 (NC/COM/NO)" H 1180 2450 50  0000 L CNN
F 2 "" H 1100 2500 50  0001 C CNN
F 3 "~" H 1100 2500 50  0001 C CNN
	1    1100 2500
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x03 J_LS2
U 1 1 E3AC1884
P 1100 2880
F 0 "J_LS2" H 1180 2930 50  0000 L CNN
F 1 "Limit Switch J2 (NC/COM/NO)" H 1180 2830 50  0000 L CNN
F 2 "" H 1100 2880 50  0001 C CNN
F 3 "~" H 1100 2880 50  0001 C CNN
	1    1100 2880
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x03 J_LS3
U 1 1 90502DC3
P 1100 3260
F 0 "J_LS3" H 1180 3310 50  0000 L CNN
F 1 "Limit Switch J3 (NC/COM/NO)" H 1180 3210 50  0000 L CNN
F 2 "" H 1100 3260 50  0001 C CNN
F 3 "~" H 1100 3260 50  0001 C CNN
	1    1100 3260
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x03 J_LS4
U 1 1 6CF36840
P 1100 3640
F 0 "J_LS4" H 1180 3690 50  0000 L CNN
F 1 "Limit Switch J4 (NC/COM/NO)" H 1180 3590 50  0000 L CNN
F 2 "" H 1100 3640 50  0001 C CNN
F 3 "~" H 1100 3640 50  0001 C CNN
	1    1100 3640
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x03 J_LS5
U 1 1 777A173D
P 1100 4020
F 0 "J_LS5" H 1180 4070 50  0000 L CNN
F 1 "Limit Switch J5 (NC/COM/NO)" H 1180 3970 50  0000 L CNN
F 2 "" H 1100 4020 50  0001 C CNN
F 3 "~" H 1100 4020 50  0001 C CNN
	1    1100 4020
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x03 J_LS6
U 1 1 1073C741
P 1100 4400
F 0 "J_LS6" H 1180 4450 50  0000 L CNN
F 1 "Limit Switch J6 (NC/COM/NO)" H 1180 4350 50  0000 L CNN
F 2 "" H 1100 4400 50  0001 C CNN
F 3 "~" H 1100 4400 50  0001 C CNN
	1    1100 4400
	1    0    0    -1  
$EndComp
Text Notes 1700 820 0    50   ~ 0
POWER NETS (recommended):
Text Notes 1700 890 0    50   ~ 0
+24V_MOTOR, GND_MOTOR (TB6600)
Text Notes 1700 960 0    50   ~ 0
+6V_SERVO, GND_SERVO (DS3240)
Text Notes 1700 1030 0    50   ~ 0
+5V_LOGIC (Pi/USB), +3V3 (ESP32)
Text Notes 1700 1100 0    50   ~ 0
Keep logic power alive when E‑Stop drops motor+servo power.
Text Notes 1700 2050 0    50   ~ 0
E‑STOP:
Text Notes 1700 2120 0    50   ~ 0
Use a latching mushroom switch.
Text Notes 1700 2190 0    50   ~ 0
Wire the motor PSU enable/relay coil through the NC chain.
Text Notes 1700 2260 0    50   ~ 0
Optionally also cut servo rail.
Text Notes 1700 2330 0    50   ~ 0
Route a separate ESTOP_STATUS signal to ESP32 for logging.
Text Notes 5100 720 0    50   ~ 0
ROBOT ESP32-S3 (suggested pin mapping – adjust to your board):
Text Notes 5100 790 0    50   ~ 0
I2C_SDA=GPIO8, I2C_SCL=GPIO9
Text Notes 5100 860 0    50   ~ 0
CAN_TX=GPIO5, CAN_RX=GPIO4
Text Notes 5100 930 0    50   ~ 0
TB6600 J1 STEP/DIR/EN: GPIO10/11/12
Text Notes 5100 1000 0    50   ~ 0
TB6600 J2 STEP/DIR/EN: GPIO13/14/15
Text Notes 5100 1070 0    50   ~ 0
TB6600 J3 STEP/DIR/EN: GPIO16/17/18
Text Notes 5100 1140 0    50   ~ 0
TB6600 J4 STEP/DIR/EN: GPIO19/20/21
Text Notes 5100 1210 0    50   ~ 0
Limit switches to remaining GPIOs (use pullups).
Text Notes 5100 3020 0    50   ~ 0
MASTER ESP32-S3:
Text Notes 5100 3090 0    50   ~ 0
Read user manipulator sensors (AS5600 via TCA9548A or pots).
Text Notes 5100 3160 0    50   ~ 0
Send joint targets over CAN at 100–250 Hz.
Text Notes 5100 3230 0    50   ~ 0
Impose deadman/foot pedal; on release transmit 'HOLD' state.
Text Notes 7700 820 0    50   ~ 0
CAN TRANSCEIVER MODULE:
Text Notes 7700 890 0    50   ~ 0
ESP32 TWAI requires an external transceiver.
Text Notes 7700 960 0    50   ~ 0
CANH/CANL twisted pair, 120Ω termination at bus ends.
Text Notes 7700 1030 0    50   ~ 0
Keep stubs short; add TVS + ferrites if noise.
Text Notes 7700 2200 0    50   ~ 0
I2C:
Text Notes 7700 2270 0    50   ~ 0
AS5600 has fixed I2C address (0x36), so multiplexing is required.
Text Notes 7700 2340 0    50   ~ 0
Use TCA9548A channels: CH0..CH5 each to one encoder.
Text Notes 7700 2410 0    50   ~ 0
Add 3.3V pullups (usually on boards already).
Text Notes 7700 5000 0    50   ~ 0
STEPPERS / TB6600:
Text Notes 7700 5070 0    50   ~ 0
TB6600 modules expect differential-like PUL+/PUL- etc.
Text Notes 7700 5140 0    50   ~ 0
If using single-ended GPIO, tie PUL+/DIR+/ENA+ to +5V
Text Notes 7700 5210 0    50   ~ 0
and drive PUL-/DIR-/ENA- with open-collector (ULN2803) or opto-compatible wiring.
Text Notes 7700 5280 0    50   ~ 0
Alternative: use STEP/DIR drivers that accept 3.3V logic directly.
Text Notes 12100 2200 0    50   ~ 0
SERVOS:
Text Notes 12100 2270 0    50   ~ 0
Use PCA9685 for DS3240 signals.
Text Notes 12100 2340 0    50   ~ 0
Feed PCA V+ from servo rail (6–8.4V), VCC from 3.3V/5V logic.
Text Notes 12100 2410 0    50   ~ 0
Common GND between logic and servo rails.
Text Notes 12100 2480 0    50   ~ 0
Allocate channels:
Text Notes 12100 2550 0    50   ~ 0
CH0=J5, CH1=J6, CH2=Tool (gripper/cutter).
Text Notes 9800 10000 0    45   ~ 0
INTEGRATION NOTE:
Text Notes 9800 10070 0    45   ~ 0
This file is a scaffold for wiring. After opening in KiCad,
Text Notes 9800 10140 0    45   ~ 0
add wires and net labels to match your exact ESP32 header pins,
Text Notes 9800 10210 0    45   ~ 0
and annotate the harness connectors you physically choose (JST/GX/XT).

$EndSCHEMATC
